.runner-tags:
  tags:
    - itup-alm-x86

stages:
  - test

crypto-metadata:
  extends: .runner-tags
  stage: test
  image: images.paas.redhat.com/exd-sp-guild-security/code-scanning:v1.1.0
  before_script:
    - python3 -m pip install "pytest>=7.4,<9" "pytest-timeout>=2.1,<3" "pyyaml"
  script:
    - python3 -m pytest tests/test_crypto_metadata.py
  rules:
    - when: always
